### ISSUE TITLE
Tracking and Discussion Issue/Thread for improved Theme Support

### ISSUE THREAD

**Issue by TayouVR** [PrismLauncher/PrismLauncher#208]
I wanted to make this issue to keep track of changes I am doing and planning for theming in Prism Launcher.

~~In #149 I am currently working on supporting several custom themes.~~ #149 is merged now, this means we can load multiple custom themes as well as standalone qss files. this makes it easier to load themes from other apps like OBS or modOrganizer2. 

TODO:

- [x] The existing format will be supported further on. (The App will look for folders in `themes/`, that contain `index.json` and read the qss file from that json (defaults to `custom-theme.css` if it doesn't have the qss file name yet))
- [x] More Themes may be added in other folders anywhere in `themes/`. 
- [x] QSS (and CSS) Files can be loaded without `index.json`, these are not guaranteed to have the correct color palette, your mileage may vary. There can be multiple of these in one folder.
- [ ] We could support the .colors files from some desktop themes and maybe even migrate our .json color palette to that format. (see https://github.com/vinceliuice/Fluent-kde/tree/main/color-schemes)
- [ ] *Maybe* implement kvantum themes
- [ ] ~~When Plasma 6 releases and the new universal theming arrives we should support that https://phabricator.kde.org/T13467~~ It doesn't look like plasma 6 actually did any major changes to theming

**Comment by ghost** [comment]
Can you add a 'compact theme' that'll fix https://github.com/PrismLauncher/PrismLauncher/issues/268

**Comment by TayouVR** [comment]
@678435021 
someone would have to make it, then we could add it. It needs to be any compatible license to be included (e.g.  GPL3.0 or any CC license). Otherwise you can just load any theme out there. Maybe there is one you like in the #themes forum on our discord.

As for the issue in your issue, try Prism Launchers "Legacy" build (the one for windows 7 & 8), that one uses a different Qt version, which doesn't scale correctly (which is what you want)

**Comment by DioEgizio** [comment]
perhaps we could support Kvantum themes, with that we could get basically every theme to work, though that's probably not easy

**Comment by TayouVR** [comment]
when talking about themes on discord a bit ago it seemed like Kvantum themes can be quite hacky, and therefore hard to implement...
But i can have a look into it.
